version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edumart_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=edumart
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: edumart_db
    restart: always
    environment:
      MYSQL_DATABASE: edumart
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
